### ISSUE TITLE
User Story: Understand Site Purpose

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#1]
As a **Site User** I can **understand the site purpose** so that **my expectations of the site are set**
  
# Acceptance Criteria
  
* As soon as a user enters the site they should be presented with the site purpose
* This should be easily understood and provide the necessary directions required
* The user should have an understanding of what to expect
  
# Tasks

- [x] Create an app called Home to create the home view
- [x] Upload the home page background image
- [x] Create the alt attribute as the image name and save
- [x] Create the index.html template to create a cover page
- [x] Add an about.html page to display the descriptive content which contains the site purpose
- [x] Ensure that the formatting and styling is pleasing
- [x] Add clear direction regarding the next steps that the user should take
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Functionality successfully implemented.
