### ISSUE TITLE
User Story: View Music Store

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#10]
As  a **Site User** I can **view the music store menu** so that **I can purchase individual products**
  
# Acceptance Criteria
  
* Category menu for music store
* Each category has a shop now button
* The links are clickable and the view opened displays the relevant products for the category selected
  
# Tasks

- [x] Create the store App
- [x] Create the products model
- [x] Create the categories model
- [x] Create the menu links from nav, adverts and home
- [x] Create the music store template
- [x] Ensure all options are included
- [x] Style with bootstrap and CSS
- [x] Make sure options are links
- [x] Test all changes

**Comment by Claire-Potter** [comment]
The store app has been successfully created
