### ISSUE TITLE
User Story: Singing Lessons

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#11]
As  a **Site User** I can **view singing lessons offered** so that **I can subscribe**
  
# Acceptance Criteria
  
* View details on singing lessons
* View various options available
  
# Tasks

- [x] Create the singing_lesson product
- [x] Integrate products through djstripe
- [x] Add various options
- [x] Add details and  image
- [x] Pull through to template and style with bootstrap and CSS
- [x] Test all changes
