### ISSUE TITLE
User Story: Piano Lessons

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#12]
As  a **Site User** I can **view piano lessons offered** so that **I can subscribe**
  
# Acceptance Criteria
  
* View details on piano lessons
* View various options available
  
# Tasks

- [x] Create the piano_lesson product
- [x] Integrate through djstripe
- [x] Add various options
- [x] Add details and images
- [x] Pull through to template and style with bootstrap and CSS
- [x] Include links to any additional information
- [x] Test all changes
