### ISSUE TITLE
User Story: Worship Workshops

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#13]
As  a ** Attendee/Booker** I can **view an available worship workshop** so that **I can set up attendance**
  
# Acceptance Criteria
  
* View details on the worship workshop
* View various options available
* View details, audio samples and images to make an informed decision
  
# Tasks

- [ ] Create the worship_workshop view, url and template
- [ ] Add various options
- [ ] Add details, audio samples and images
- [ ] Style with bootstrap and CSS
- [ ] Include links to any additional information
- [ ] Test all changes
