### ISSUE TITLE
User Story: Music Store Product

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#14]
As  a **Site User** I can **view an individual product** so that **I can decide whether to make a purchase or not**
  
# Acceptance Criteria
  
* View details on the product
* View price, specifications and delivery options
* View details and images to make an informed decision
  
# Tasks

- [x] Create the music store product view, url and template
- [x] Add details and images
- [x] Style with bootstrap and CSS
- [x] Include links to any additional information
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Functionality completed successfully
