### ISSUE TITLE
User Story: Identify Specials and Sales

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#15]
As  a **Site User** I can **easily view any subscriptions special offers, and delivery deals** so that **I can take advantage of the offer**
  
# Acceptance Criteria
  
* View any specials on subscriptions
* View any delivery discounts
* Receive all specials/deals via an email
  
# Tasks

- [x] Create a section on all pages to advertise any specials/deals/sales
- [x] Include lessons, workshops and store sections across all pages as advertisements for the services and products
- [x] Ensure when the site user selects the subscription/product,  for annual subscription a 7 day trial is created and for products over 40 pounds the new shipping discounted price reflects
- [x] If a certain number of products needs to be purchased to receive the discount make sure that this calculates correctly
- [x] Test all changes
