### ISSUE TITLE
User Story:  Subscriptions and Purchases

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#17]
As a **Site User** I can **purchase and cancel subscriptions and purchase products** so that **I can utilise all services and purchase goods from the same site**
  
# Acceptance Criteria
  
* The same user can purchase subscriptions and choose to set up whether to pay annually, monthly or weekly as well 
* Select multiple products to purchase, have the total reflect all products and pay for the items upfront
  
# Tasks

- [x] Set up the different subscription options per lesson
- [x] Set up billing for products and make sure sub-totals and totals calculate correctly
- [x] Make sure one user has access to perform both tasks
- [x] Test all changes
