### ISSUE TITLE
User Story: Create an Account

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#19]
As  a **Site User** I can **create/register for an account** so that **I can create a user profile and save my personal information**
  
# Acceptance Criteria
  
* I can create a simple account
* I can save my personal information
* I can view sections that require me to be logged in
* I can perform site actions that require me to be logged in
  
# Tasks

- [x] Install and enable django allauth
- [x] Customise the default account templates
- [x] Create a user profile model to store information
- [x] Create the necessary view/s url/s and template/s
- [x] Test all changes
