### ISSUE TITLE
User Story: Login and Logout

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#20]
As a **Site User** I can **easily login or logout of my account** so that **I can update my personal profile and access user sections**
  
# Acceptance Criteria
  
* A non-logged-in will have the option to register or log in from their navigation
* A user can easily log in to their account, once logged in they will have the option to logout from their navigation
* When logged in the user can update their personal user profile and view/action restricted pages/content for logged-in users only
  
# Tasks

- [x] Customise the default login/logout templates
- [x] Update the navigation to reflect the login or log out option within the menu if the user is logged in or not
- [x] Make sure the user profile can only be viewed and updated once a user is logged in
- [x] Make sure that any pages with restricted access, are updated to allow logged-in users to access
- [x] Test all changes
