### ISSUE TITLE
User Story: Password Recovery

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#21]
As a **Site User** I can **recover my password** so that **I can continue to access my account**
  
# Acceptance Criteria
  
* If I have forgotten my password I can request to reset it
* A reset password email with a link will be sent
* I can open the link and reset my password and proceed to login to my account
  
# Tasks

- [x] Ensure that the login page includes a forgot password link
- [x] Allow the user to capture their email address to reset their password
- [x] Customise all necessary templates
- [x] Test that all functionality works correctly
