### ISSUE TITLE
User Story: Email Confirmation

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#22]
As a **Site User** I can **receive an email confirmation upon registration** so that **my registration is confirmed**
  
# Acceptance Criteria
  
* Once I have successfully registered an email confirmation is sent
* The email confirmation is received in the inbox I have registered with
* A link in the confirmation email takes me to login to my account
  
# Tasks

- [x] Create an email template to confirm registration
- [x] Set up send email functionality to send the email
- [x] Check that the link in the email opens the login page
- [x] Test all changes
