### ISSUE TITLE
User Story: Sort the Music Store Products

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#24]
As  a **Site User** I can **sort the music store products** so that **I can easily find what product I am searching for**
  
# Acceptance Criteria
  
* I can sort the music store products according to various options
* I can sort the music store products within a specific category
* I can sort the music store products across categories
  
# Tasks

- [x] Set up the various filter options to allow the user to sort accordingly
- [x] Set up the views to render the product information accordingly
- [x] Test all changes

**Comment by Claire-Potter** [comment]
The sort functionality has been successfully implemented
