### ISSUE TITLE
User Story: Select Quantity

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#25]
As a **Site User** I can **select the correct quantity** so that **I can buy the correct number of products I require**
  
# Acceptance Criteria
  
* When adding a product to the shopping bag I can select the quantity
* The correct quantity appears in the bag and the sub-total and totals update correctly  
# Tasks

- [x] Add the option to select quantity when adding a product to the bag
- [x] Set up the basket to calculate sub-total of product according to quantity 
- [x] Ensure total includes all sub-totals and calculates correctly
- [x] Test all changes
