### ISSUE TITLE
User Story: View items in Shopping Bag

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#27]
As a **Site User** I can **view all items added to my shopping bag** so that **I can see what I am purchasing and the total cost**
  
# Acceptance Criteria
  
* View a summarised view of all products added to the shopping bag
* View amount and sub-total per product
* View total amount for all products
  
# Tasks

- [x] Create the Shopping Bag App
- [x] Set up view URL and template for the shopping bag
- [x] Add the shopping bag to the navigation
- [x] Add ability for user to add products to the shopping bag
- [x] Ensure total displays correctly
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Successfully created the shopping bag app
