### ISSUE TITLE
User Story: Lesson Checkout and Add Subscription

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#28]
As a **Site User** I can **proceed to checkout, pay for the subscription and add subscription details** so that **I can subscribe to a lesson**
  
# Acceptance Criteria
  
* The correct pricing appears on the checkout page and I can capture my payment details
* I can add my details and student name to the subscription
* A subscription summary is generated and displayed
* I can access the Invoice on Stripe from the subscription summary

# Tasks

- [x] Set up a checkout page to capture payment details
- [x] Set up integration with Stripe to create the customer, subscription and recurring payment
- [x] Send the details from stripe back to the database
- [x] Add additional subscription details and save subscription
- [x] Create page to display subscription details
- [x] Ensure all information pulls through correctly
- [x] Test all changes
