### ISSUE TITLE
User Story: User Profile and Subscriptions

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#29]
As a **Site User** I can **create multiple subscriptions and add student details** so that **I can manage all family subscriptions from one account**
  
# Acceptance Criteria
  
* When a user sets up their subscriptions they can add student details
* I am able to see the student assigned to the subscription from my profile
  
# Tasks

- [x] When a user registers for a subscription they can add the student's name
- [x] Display the subscription and student name on the profile page
- [x] Test all changes
