### ISSUE TITLE
User Story: Navigation

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#3]
As a **Site User** I can **easily Navigate across all site pages** so that **I can view all content logically and without hassle**

# Acceptance Criteria
  
* The Navigation menu is located in a visible page section
* The menu items are logical and all links open the correct pages
* The Navigation menu items will display according to the user's logged-in status
* If the user is a staff member, they will also have access to the Admin site and additional pages
* The Navigation menu will re-size for smaller screens and will display as the navigation 'hamburger'
  
# Tasks

- [x] Create the navigation section within the header section on base.html to ensure it is the same across all pages and maintained in one template
- [x] Add the various menu links and make sure the link is for the correct page
- [x] Add an if statement used to check if the user is logged in or not, within the template
- [x] Add an if statement used to check if the user is staff or not, within the template
- [x] Use bootstrap classes and CSS to style the navigation menu across screen sizes
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Functionality successfully completed
