### ISSUE TITLE
User Story: Add Worship Workshops Attendees

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#30]
As a ** Attendee/ Booker** I can **select to add one attendee or multiple attendees** so that **I can schedule the correct number of people to attend the worship workshop**
  
# Acceptance Criteria
  
* I can add a single attendee to my shopping bag
* I can add multiple attendees to my shopping bag
* The correct pricing appears in the bag and the sub-total and totals update correctly  

# Tasks

- [ ] Add the option to select or one attendee
- [ ] Set up the basket to calculate sub-total for attendees
- [ ] Ensure total includes all sub-totals and calculates correctly
- [ ] Test all changes
