### ISSUE TITLE
User Story: Adjust item quantity in the shopping bag

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#31]
As  a **Site User** I can **adjust the number of items in my shopping bag** so that **I purchase the correct amount**
  
# Acceptance Criteria
  
* I can increase or decrease the quantity of a product I wish to purchase
  
# Tasks

- [x] Create a view for the shopping bag
- [x] Create a form for the user to edit the quantity field
- [x] Ensure there is a minimum quantity value and a maximum quantity value
- [x] Ensure all sub-totals and totals calculate correctly
- [x] Test all changes
