### ISSUE TITLE
User Story: Easily Checkout

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#32]
As a **Site User** I can **easily checkout and capture my payment information** so that **I experience an efficient service**
  
# Acceptance Criteria
  
* If I have an account, I can save my payment details to my account
* If I don't have an account I can choose to capture my payment details when checking out
* Checkout process runs smoothly and optimally
  
# Tasks

- [x] Create a checkout view, URL and template
- [x] As a user with an account, I can choose to save my address details to my account
- [x] As a user without an account I can still complete and save the payment form
- [x] If I create an account afterwards, those payment details will be saved to my account
- [x] Test all changes
