### ISSUE TITLE
User Story: Secure personal and payment information

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#33]
As a **Site User** I can **rest assured that all personal and payment information that I capture is secure** so that **I know my data and account is secure**
  
# Acceptance Criteria
  
* Payment through Stripe.com is enabled
* No sensitive personal or payment data is visible to anyone but the site user
* Security measures are in place to ensure the safety of payments
  
# Tasks

- [X] Integration with stripe is set up 
- [X] Stripe settings are added
- [X] Strip card payment can be captured
- [x] Test all Changes
