### ISSUE TITLE
User Story: View order confirmation 

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#34]
As a **Site User** I can **view an order confirmation once I have checked out** so that **I can confirm all the details and the purchase is correct*
  
# Acceptance Criteria
  
* Once a product/subscription/programme has been purchased, I can view all details after checkout
* A copy of the order details is saved to my profile and I can view this
* A copy of the order  receipt is emailed to me
* If any details are incorrect I can contact the site admin to assist
  
# Tasks

- [x] Once checkout is complete create a view to display order confirmation and details
- [x] On a user's profile  a copy of all orders is saved here
- [x] Test all changes
