### ISSUE TITLE
User Story: Update products and subscriptions

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#35]
As the **Site Owner / Admin** I can **Update products and lessons** so that **I can maintain my offerings**
  
# Acceptance Criteria
  
* A Site Owner/Admin has access from the front end to maintain all products in the music shop - Add, Update or Archive
* A Site Owner has access from the front end to maintain all available lessons - Add or Update
  
# Tasks

- [x] Create an Admin Maintainenance  view, template and URLs for admin users, to access and maintain products and lessons from the frontend
- [x] Ensure access is only available to staff
- [x] Create a front end view of the relevant models
- [x] Create forms for the admin users to update the relevant models from the front end
- [x] Test all changes
