### ISSUE TITLE
User Story: Site Owner, Site Admin and Super User  Users

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#36]
As a **Site Owner / Site Admin / Super User** I can **access the Admin facility as well as maintain items on the front end** so that **I can actively support customers and manage my business**
  
# Acceptance Criteria
  
* Site Owner has specific access assigned
* Site Admin has specific access assigned
* Super User has full access apart from restrictions in code and only applicable djstripe models reflected in site admin.
  
# Tasks

- [x] Create the Site Owner group and assign the necessary authorisation
- [x] Create the Site Admin group and assign the necessary authorisation
- [x] Create the Super User with no access group restrictions, only restrictions from code
- [x] Ensure all groups have one user account assigned
- [x] Test that all authorisations added work correctly on the Site Admin page as well as on the front end site
