### ISSUE TITLE
User Story: Student Showcase

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#38]
As the **Site Owner / Site Admin** I can **showcase a student on the about page** so that **I can show off their talents**
  
# Acceptance Criteria
  
* A Site Owner / Admin can create posts that will be displayed on the About page.
* The post will include an image and a video if uploaded
* The customer and subscription are linked to the post
  
# Tasks

- [x] Create the Student Showcase Model
- [x] Ensure an image and a video field are included
- [x] Include customer and subscription as foreign fields
- [x] Create a form for the staff to capture student showcase specifics from the front end
- [x] Create the view, URL and template for adding student showcases
- [x] In the About view pull through the latest student showcase
- [x] Create the student showcase advert to be included on the about page
