### ISSUE TITLE
User Story: Contact Request

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#4]
As a **Site User** I can **create and submit a contact request** so that **I can receive support from the site admin or owner**
  
# Acceptance Criteria
  
* A User is able to capture a message
* The contact request is saved and admin can access it from the Admin site 
* An email is sent to the admin email address containing the name, email address and contact message of the user
  
# Tasks

- [x] Create the contact model within the home app
- [x] Create the contact form
- [x] Create the view to capture, post, save and send the request
- [x] Create the url and the template and styl with bootstrap and css
- [x] Add the contact link to the navigation
- [x] Test all changes

**Comment by Claire-Potter** [comment]
Completed Contact Us page
