### ISSUE TITLE
User Story: Music Lesson Bag

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#43]
As  a **Site User** I can **add a lesson to the music lesson bag** so that **I can view the lesson and proceed to checkout**
  
# Acceptance Criteria
  
* The correct details of the lesson reflect in the music lesson bag
* A miniature version of the music lesson bag reflects in the success message
*  The user can select to remove the lesson from the bag
* The user can proceed to checkout from inside the bag
  
# Tasks

- [x] Create the music lesson bag page
- [x] Set up functionality to add lessons to the bag
- [x] Set up the music lesson bag success message
- [x] Set up functionality to remove a lesson from the bag and add remove button
- [x] Include a link to the checkout page
- [x] Test all changes
