### ISSUE TITLE
User Story: Pop up Messages

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#44]
As  a **User** I can **view success, info, error and alert messages** so that **I am alerted of the impact of my actions**
  
# Acceptance Criteria
  
* When a user adds items to the shopping bag, a success message displays and previews the items in the bag
* When a user logs in logs out success messages displays
* If any errors or alerts occur, success messages display
  
# Tasks

- [x] Create toast templates for the various message types
- [x] Add a messages area to base.html to display the messages
- [x] Style the messages
- [x] Add the messages to the various shopping bag views
- [x] Test all changes
