### ISSUE TITLE
User Story: Songwriting Lessons

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#51]
As  a **Site User** I can **view songwriting lessons offered** so that **I can subscribe**
  
# Acceptance Criteria
  
* View details on songwriting lessons
* View various options available
  
# Tasks

- [x] Create the songwriting_lesson view, url and template
- [x] Add various options
- [x] Add details and images
- [x] Style with bootstrap and CSS
- [x] Include links to any additional information
- [x] Test all changes
