### ISSUE TITLE
User Story: View Lessons

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#8]
As  a **Site User** I can **view available lessons offered** so that **I can subscribe**
  
# Acceptance Criteria
  
* Info on singing lessons displays
* Info on piano lessons displays
*Info on songwriting lessons displays
* The links are clickable and direct the user to order a subscription
  
# Tasks

- [x] Create the Lessons App
- [x] Create the lesson model
- [x] Create the type model
- [x] Create the subscriptions model
- [x] Create lessons.html
- [x] Ensure all lesson options are included
- [x] Style with bootstrap and CSS
- [x] Make sure subscription links are included
- [x] Test all changes
