### ISSUE TITLE
User Story: View Worship Workshops

### ISSUE THREAD

**Issue by Claire-Potter** [Claire-Potter/Belle-Musique-Studio#9]
As  a ** Attendee/Booker** I can **view the link to worship workshops** so that **I can subscribe for an individual or a team to attend**
  
# Acceptance Criteria
  
* Dropdown menu for worship workshops
* The links are clickable
  
# Tasks

- [x] Create the Worshop App
- [ ] Create the workshop model
- [ ] Create the dropdown menus
- [ ] Ensure all options are included
- [ ] Style with bootstrap and CSS
- [ ] Make sure options are links
- [ ] Test all changes
